version: '3'

volumes:
  postgres_data:

services:
  web:
    build: .
    volumes:
      - ./sample:/var/www/html
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: huser
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: codeigniter
    tty: true
